from .ukge_loss import UKGELoss
from .passleaf_loss import PASSLEAFLoss
from .beurre_loss import BEUrRELoss
from .ukgse_loss import UKGsELoss
from .ukge_psl_loss import UKGEPSLLoss
from .focuse_loss import FocusELoss
from .gtranse_loss import GtransELoss
from .upgat_loss import UPGATLoss
from .gmuc_loss import GMUCLoss